### ISSUE TITLE
Release rqt_robot_plugins 0.4.2

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_robot_plugins#88]
- [x] Need to rename master branch
- [x] ~~Need to keep hydro-devel branch~~
- [x] ~~Need to roll back https://github.com/ros-visualization/rqt_robot_plugins/commit/06e51d1f5b4ed9c926f28779054ba143a016bcc9 in hydro-devel since 3 as stale does not exist in hydro.~~
- [x] update tracks files with new master branch!
- [x] Release for ~~groovy, hydro~~, indigo and Jade

**Comment by dirk-thomas** [comment]
Why is that necessary? While in hydro the level can never be 3 the patch does not harm on hydro.

**Comment by ablasdel** [comment]
Yeah you are right it will never be 3 so i guess it is innocuous. Still want to release and make an indigo-devel branch.

**Comment by ablasdel** [comment]
My plan is change the branch name for each LTS. Does that sound OK?

That said maybe we should steer away from this and just go back to "master" which is used on everything unless there is a specific conflict and then we can spin off a backports branch? That way the branch name never gets stale.

**Comment by dirk-thomas** [comment]
That is okay with me. You need to update all references in the distribution files as well the gbp repo for that.

Also keep in mind that such a change requires everybody who has a checkout to switch to the new branch.

Btw. there will certainly not be a groovy release anymore since groovy packages are not being built anymore. And for hydro you should be dead certain that the new release doesn't break anything because you might not get another shot to release into hydro once the build farm is retired (which can happen anytime after it is EOLes which is already the case).

**Comment by ablasdel** [comment]
Hydro doesn't need a release then. that commit doesn't actually change anything on hydro

**Comment by ablasdel** [comment]
Just planning to do indigo & jade then

**Comment by dirk-thomas** [comment]
Sounds good to me.

**Comment by ablasdel** [comment]
Done and done
